language: python

notifications:
  email: false

addons:
  apt:
    packages:
      - python-dev
      - python3-dev
      - swig

sudo: required

matrix:
  include:
  - os: linux
    dist: trusty
    python: '2.6'
  - os: linux
    dist: trusty
    python: '2.7'
  - os: linux
    dist: trusty
    python: '3.3'
  - os: linux
    dist: trusty
    python: '3.4'
  - os: linux
    dist: trusty
    python: '3.5'
  - os: osx
    language: objective-c
    env: PYENV_VERSION=2.7.11
  - os: osx
    language: objective-c
    env: PYENV_VERSION=3.5.1

before_install:
- |
  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    brew update
    brew install swig
    brew outdated openssl || brew upgrade openssl
    brew outdated cmake || brew upgrade cmake
  fi
- python -V

script:
- ./travis.sh


