language: cpp

git:
  depth: 10

notifications:
  email: false

addons:
  apt:
    packages:
      - libssl-dev
      - python-dev
      - scons
      - swig

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
    - os: osx
      compiler: clang

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
- |
  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    brew update
    brew install swig
    brew outdated openssl || brew upgrade openssl
    brew outdated cmake || brew upgrade cmake
  fi
- python -V

script:
- ./travis.sh


