language: python

notifications:
  email: false

addons:
  apt:
    packages: &native_deps
      - swig

sudo: required

matrix:
  include:
      #  - os: linux
      #    dist: trusty
      #    python: '2.6'
      #    addons:
      #      apt:
      #        packages:
      #          - *native_deps
      #          - python-dev
  - os: linux
    dist: trusty
    python: '2.7'
    addons:
      apt:
        packages:
          - *native_deps
          - python-dev
      #  - os: linux
      #    dist: trusty
      #    python: '3.2'
      #    addons:
      #      apt:
      #        packages:
      #          - *native_deps
      #          - python3-dev
      #  - os: linux
      #    dist: trusty
      #    python: '3.3'
      #    addons:
      #      apt:
      #        packages:
      #          - *native_deps
      #          - python3-dev
      #  - os: linux
      #    dist: trusty
      #    python: '3.4'
      #    addons:
      #      apt:
      #        packages:
      #          - *native_deps
      #          - python3-dev
      #  - os: linux
      #    dist: trusty
      #    python: '3.5'
      #    addons:
      #      apt:
      #        packages:
      #          - *native_deps
      #          - python3-dev
      #  - os: osx
      #    language: generic
      #    env: PYENV_VERSION=2.7.11
      #  - os: osx
      #    language: generic
      #    env: PYENV_VERSION=3.5.1

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update
      brew install swig
      brew outdated openssl || brew upgrade openssl
      brew outdated cmake || brew upgrade cmake
    fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install scons; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install scons; fi
  - python -V

script:
  - ./travis.sh
